
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 19 11:25:05 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 7;
  public static final int GE = 30;
  public static final int SLASH = 26;
  public static final int NUMCONST = 47;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 41;
  public static final int SEMI = 37;
  public static final int CONTINUE = 19;
  public static final int MINUS = 24;
  public static final int LSQ = 45;
  public static final int STAR = 25;
  public static final int RPAREN = 42;
  public static final int AND = 34;
  public static final int LT = 33;
  public static final int RECORD = 20;
  public static final int OR = 35;
  public static final int COMMA = 39;
  public static final int CLASS = 4;
  public static final int INC = 21;
  public static final int PLUS = 22;
  public static final int ASSIGN = 36;
  public static final int IF = 8;
  public static final int THIS = 11;
  public static final int DOT = 40;
  public static final int LE = 32;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int EQUAL = 28;
  public static final int SUPER = 10;
  public static final int NEW = 13;
  public static final int error = 1;
  public static final int PERCENT = 27;
  public static final int RSQ = 46;
  public static final int IDENT = 48;
  public static final int BREAK = 3;
  public static final int VOID = 17;
  public static final int COLON = 38;
  public static final int LBRACE = 43;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 15;
  public static final int CHARCONST = 49;
  public static final int WHILE = 12;
  public static final int RBRACE = 44;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int DEC = 23;
  public static final int GT = 31;
  public static final int PRINT = 14;
  public static final int DO = 9;
}

